version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /app
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    entrypoint: ["./docker/entrypoint.sh", "./cmd/main.go"]


  migrate:
    image: migrate/migrate
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    profiles:
      - donotstart
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zikr_app
    ports:
      - "5432"
