CREATE TABLE IF NOT EXISTS "zikr" (
    "id" SERIAL PRIMARY KEY,
    "arabic" TEXT NOT NULL,
    "uzbek" TEXT NOT NULL,
    "pronounce" TEXT NOT NULL,
    "created_at" TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
