// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app-version": {
            "get": {
                "description": "This API gets app version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app-version"
                ],
                "summary": "Get app version",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/model.AppVersion"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "This API updates app version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app-version"
                ],
                "summary": "Update app version",
                "parameters": [
                    {
                        "description": "app version",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AppVersion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/model.AppVersion"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "register-user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get or Create user",
                "parameters": [
                    {
                        "description": "account info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/model.UserGuid"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users-zikr/count": {
            "patch": {
                "description": "This API updates zikr count",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-zikr"
                ],
                "summary": "Update zikr count",
                "parameters": [
                    {
                        "description": "account info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Count"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users-zikr/favorite": {
            "patch": {
                "description": "This API update zikr favorite",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-zikr"
                ],
                "summary": "Update zikr favorite",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.IsFavorite"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated to favorite",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "could not update",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users-zikr/reyting": {
            "get": {
                "description": "This API count zikr",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-zikr"
                ],
                "summary": "Count zikr",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "zikr_guid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/model.ReytingResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "could not update",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/zikr": {
            "get": {
                "description": "This API gets a list of zikr",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zikr"
                ],
                "summary": "Get zikr list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GUID of the user",
                        "name": "guid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/model.Zikrs"
                        }
                    },
                    "404": {
                        "description": "Error response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "This API updates a zikr",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zikr"
                ],
                "summary": "Update zikr",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GUID of the zikr",
                        "name": "zikrId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Zikr"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Error response",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "create-zikr",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zikr"
                ],
                "summary": "Create zikr",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Zikr"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "This api Delete zikr",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zikr"
                ],
                "summary": "Delete zikr",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GUID of the zikr",
                        "name": "zikrId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AppVersion": {
            "type": "object",
            "properties": {
                "android_version": {
                    "type": "string"
                },
                "force_update": {
                    "type": "boolean"
                },
                "ios_version": {
                    "type": "string"
                }
            }
        },
        "model.Count": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "user_guid": {
                    "type": "string"
                },
                "zikr_guid": {
                    "type": "string"
                }
            }
        },
        "model.GetZikr": {
            "type": "object",
            "properties": {
                "arabic": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "guid": {
                    "type": "string"
                },
                "is_favorite": {
                    "type": "boolean"
                },
                "pronounce": {
                    "type": "string"
                },
                "uzbek": {
                    "type": "string"
                }
            }
        },
        "model.IsFavorite": {
            "type": "object",
            "properties": {
                "is_favorite": {
                    "type": "boolean"
                },
                "user_guid": {
                    "type": "string"
                },
                "zikr_guid": {
                    "type": "string"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string"
                }
            }
        },
        "model.Reyting": {
            "type": "object",
            "required": [
                "limit",
                "page"
            ],
            "properties": {
                "limit": {
                    "type": "integer",
                    "default": 10
                },
                "page": {
                    "type": "integer",
                    "default": 1
                },
                "zikr_guid": {
                    "type": "string"
                }
            }
        },
        "model.ReytingResponse": {
            "type": "object",
            "properties": {
                "reytings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Reyting"
                    }
                }
            }
        },
        "model.UserGuid": {
            "type": "object",
            "properties": {
                "guid": {
                    "type": "string"
                }
            }
        },
        "model.UserLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.Zikr": {
            "type": "object",
            "properties": {
                "arabic": {
                    "type": "string"
                },
                "pronounce": {
                    "type": "string"
                },
                "uzbek": {
                    "type": "string"
                }
            }
        },
        "model.Zikrs": {
            "type": "object",
            "properties": {
                "zikrs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.GetZikr"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "Created by Otajonov Quvonchbek and Usmonov Azizbek",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
