definitions:
  model.GetZikr:
    properties:
      arabic:
        type: string
      id:
        type: string
      pronounce:
        type: string
      uzbek:
        type: string
    type: object
  model.Id:
    properties:
      id:
        type: string
    type: object
  model.SignIn:
    properties:
      password:
        type: string
      phone_number:
        example: "998999999999"
        type: string
    type: object
  model.User:
    properties:
      fio:
        type: string
      password:
        type: string
      phone_number:
        example: "998999999999"
        type: string
      uniqeUsername:
        type: string
    type: object
  model.Zikr:
    properties:
      arabic:
        type: string
      pronounce:
        type: string
      uzbek:
        type: string
    type: object
  model.Zikrs:
    properties:
      zikrs:
        items:
          $ref: '#/definitions/model.GetZikr'
        type: array
    type: object
info:
  contact: {}
  description: Created by Otajonov Quvonchbek
paths:
  /v1/create:
    post:
      consumes:
      - application/json
      description: This api can create new zikr
      parameters:
      - description: Create
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Zikr'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Id'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create zikr
      tags:
      - Zikr
  /v1/delete:
    delete:
      consumes:
      - application/json
      description: This api can delete zikr
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Delete zikr
      tags:
      - Zikr
  /v1/get:
    get:
      consumes:
      - application/json
      description: This api can get by ID zikr
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Zikr'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get by ID zikr
      tags:
      - Zikr
  /v1/get-all:
    get:
      consumes:
      - application/json
      description: This api can get all zikr
      produces:
      - application/json
      responses:
        "200":
          description: Created successfully
          schema:
            $ref: '#/definitions/model.Zikrs'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get all zikr
      tags:
      - Zikr
  /v1/sign-in:
    post:
      consumes:
      - application/json
      description: This api can Sign-In user
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.SignIn'
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            type: string
      summary: Sign-In user
      tags:
      - User
  /v1/sign-up:
    post:
      consumes:
      - application/json
      description: This api can Sign-Up new user
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            type: string
      summary: Sign-Up user
      tags:
      - User
  /v1/update:
    put:
      consumes:
      - application/json
      description: This api can update zikr
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      - description: Create
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Zikr'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Id'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update zikr
      tags:
      - Zikr
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
