definitions:
  domain.UserLoginRequest:
    properties:
      email:
        type: string
      unique_username:
        type: string
    type: object
info:
  contact: {}
  description: Created by Otajonov Quvonchbek and Usmonov Azizbek
paths:
  /user/check-or-register:
    post:
      consumes:
      - application/json
      description: This api can Get or Create new user
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.UserLoginRequest'
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get or Create user
      tags:
      - User
swagger: "2.0"
