definitions:
  model.AppVersion:
    properties:
      android_version:
        type: string
      force_update:
        type: boolean
      ios_version:
        type: string
    type: object
  model.Count:
    properties:
      count:
        type: integer
      user_guid:
        type: string
      zikr_guid:
        type: string
    type: object
  model.GetZikr:
    properties:
      arabic:
        type: string
      count:
        type: integer
      guid:
        type: string
      is_favorite:
        type: boolean
      pronounce:
        type: string
      uzbek:
        type: string
    type: object
  model.IsFavorite:
    properties:
      is_favorite:
        type: boolean
      user_guid:
        type: string
      zikr_guid:
        type: string
    type: object
  model.Response:
    properties:
      result:
        type: string
    type: object
  model.UserGuid:
    properties:
      guid:
        type: string
    type: object
  model.UserLoginRequest:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
  model.Zikr:
    properties:
      arabic:
        type: string
      pronounce:
        type: string
      uzbek:
        type: string
    type: object
  model.Zikrs:
    properties:
      zikrs:
        items:
          $ref: '#/definitions/model.GetZikr'
        type: array
    type: object
info:
  contact: {}
  description: Created by Otajonov Quvonchbek and Usmonov Azizbek
paths:
  /app-version:
    get:
      consumes:
      - application/json
      description: This API gets app version
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/model.AppVersion'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get app version
      tags:
      - app-version
    put:
      consumes:
      - application/json
      description: This API updates app version
      parameters:
      - description: app version
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AppVersion'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/model.AppVersion'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Update app version
      tags:
      - app-version
  /count:
    patch:
      consumes:
      - application/json
      description: This API updates zikr count
      parameters:
      - description: account info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Count'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Update zikr count
      tags:
      - zikr-count
  /favorite:
    patch:
      consumes:
      - application/json
      description: This API marks zikr as favorite
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.IsFavorite'
      produces:
      - application/json
      responses:
        "200":
          description: updated to favorite
          schema:
            type: string
        "400":
          description: invalid request body
          schema:
            type: string
        "404":
          description: could not update
          schema:
            type: string
      summary: Mark zikr as favorite
      tags:
      - zikr-favorite
  /user:
    post:
      consumes:
      - application/json
      description: register-user
      parameters:
      - description: account info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/model.UserGuid'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get or Create user
      tags:
      - user
  /zikr:
    get:
      consumes:
      - application/json
      description: This API gets a list of zikr
      parameters:
      - description: GUID of the user
        in: query
        name: guid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/model.Zikrs'
        "404":
          description: Error response
          schema:
            type: string
      summary: Get zikr list
      tags:
      - zikr
    post:
      consumes:
      - application/json
      description: create-zikr
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Zikr'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create zikr
      tags:
      - zikr
swagger: "2.0"
