env: "local" # local, prod
environment: "develop"
logLevel: "info"
storage_path: ""

http_server:
  address: "localhost:50055"
  timeout: 4s
  idle_timeout: 60s
  user: ""
  password: ""

postgres:
  postgres_host: "db"
  postgres_port: "5432"
  postgres_user: "postgres"
  postgres_password: "postgres"
  postgres_database: "zikr_app"

